
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: MINGW32_NT-10.0-19045 - 3.5.3.x86_64 - unknown
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /mingw32/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        /home/grovy/RingRacers-SKWT/src/CMakeFiles/3.26.4/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /mingw32/bin/CC.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        /home/grovy/RingRacers-SKWT/src/CMakeFiles/3.26.4/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-WwkmVp"
      binary: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-WwkmVp"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-WwkmVp
        
        Run Build Command(s):/usr/bin/cmake.exe -E env VERBOSE=1 D:Documentsninjaninja.exe -f Makefile cmTC_28c7b/fast && No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt"
    checks:
      - "Check for working C compiler: /mingw32/bin/cc.exe"
    directories:
      source: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-GWPp41"
      binary: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-GWPp41"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: /home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-GWPp41
        
        Run Build Command(s):/usr/bin/cmake.exe -E env VERBOSE=1 D:Documentsninjaninja.exe -f Makefile cmTC_ac7be/fast && No such file or directory
        
      exitCode: 1
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /mingw32/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        /home/grovy/RingRacers-SKWT/src/CMakeFiles/3.26.4/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /mingw32/bin/CC.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        /home/grovy/RingRacers-SKWT/src/CMakeFiles/3.26.4/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-tMuX2N"
      binary: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-tMuX2N"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_WARN_DEPRECATED: "FALSE"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-tMuX2N
        
        Run Build Command(s):/usr/bin/cmake.exe -E env VERBOSE=1 D:Documentsninjaninja.exe -f Makefile cmTC_5584d/fast && No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt"
    checks:
      - "Check for working C compiler: /mingw32/bin/cc.exe"
    directories:
      source: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-lQ9F2u"
      binary: "/home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-lQ9F2u"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_WARN_DEPRECATED: "FALSE"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: /home/grovy/RingRacers-SKWT/src/CMakeFiles/CMakeScratch/TryCompile-lQ9F2u
        
        Run Build Command(s):/usr/bin/cmake.exe -E env VERBOSE=1 D:Documentsninjaninja.exe -f Makefile cmTC_92a90/fast && No such file or directory
        
      exitCode: 1
...
